### ISSUE TITLE
Capitalisation on top-level FORs

### ISSUE THREAD

**Issue by dedickinson** [anzsrco/anzsrco#1]
The top level FORs are in upper case (for08.ns) as are the SEO's. We've had a request to display these in ReDBox using the same capitalisation of the child entries.

Would there be any concern in changing these? If not, I can do this. If there is, we can do some text munging in ReDBox.

**Comment by gweis** [comment]
Hi Duncan,

This should not be a problem. I find it annoying myself, that the titles are all caps.

cheers,

Gerhard

**Comment by dedickinson** [comment]
Thanks Gerhard,

I edited the files and created a Pull request. I think I've done this correctly but am eager to find out if I did it incorrectly - please let me know of any concerns.

Cheers,

Duncan

**Comment by gweis** [comment]
Hi,

It's the first time for me too, to handle pull requests. Looks like you did everything right. It merged cleanly.

cheers,

Gerhard

**Comment by dedickinson** [comment]
Hi Gerhard,

I wasn't sure which tool you used for the n3 -> rdf conversions. Is it worth me providing these renditions as well?

Cheers,

Duncan

**Comment by gweis** [comment]
Hi Duncan,

The tool to generate the rdf data is in the same repository. Everything needed to rebuild the n3 files is located in the master branch.

The folder anzsrc_data contains a couple of csv files, which probably should be updated too. The gh-pages branch is maintained separately anyway. So it does not really matter which one is updated first.

cheers,

Gerhard
